### ISSUE TITLE
Suggested list of Decanter URL's to include

### ISSUE THREAD

**Issue by agsdot** [SU-SWS/Awesome-Decanter#1]

**Comment by agsdot** [comment]
- https://decanter.stanford.edu/
- https://github.com/SU-SWS/decanter
- https://decanter-v7.netlify.app/
- https://dev-decanter-v7.netlify.app/

**Comment by sherakama** [comment]
Websites built with Decanter
* https://earth.stanford.edu
* https://engineering.stanford.edu/
* https://alumni.stanford.edu
* https://giving.stanford.edu

Themes/Tools/Frameworks
* Stanford Basic - Drupal Theme (https://github.com/su-sws/stanford_basic/)
* Redwood -  Wordpress Theme (https://drive.google.com/file/d/1VWwgp0pWy6pANO-i7LBSFJr-U1khhQWp/view?usp=sharing)
* Backdrop Theme (https://github.com/borisay/backdrop_decanter)
* Jumpstart UI - Drupal Components (https://github.com/SU-SWS/jumpstart_ui)
* https://decanter-react.netlify.app

**Comment by agsdot** [comment]
Thanks @sherakama

**Comment by agsdot** [comment]
Added links to awesome links in git commit https://github.com/SU-SWS/Awesome-Decanter/commit/9c1d83b4167ca45843f45b5ac6946758fff9b19d
